# Generated by Django 4.2.25 on 2025-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guitars",
            fields=[
                (
                    "sku",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("asn", models.CharField(max_length=256, null=True)),
                ("Category", models.CharField(max_length=256)),
                ("online", models.CharField(max_length=256)),
                ("itemName", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256, null=True)),
                ("brandName", models.CharField(max_length=256)),
                ("productDetail", models.TextField()),
                ("SalesPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pictureMain", models.ImageField(upload_to="")),
                ("qtyInStock", models.IntegerField(default=0)),
                ("qtyOnOrder", models.IntegerField(default=0)),
                ("colour", models.IntegerField()),
                ("pickup", models.IntegerField()),
                ("BodyShape", models.IntegerField()),
                ("CreatedOn", models.DateField()),
                ("rating", models.DecimalField(decimal_places=2, max_digits=10)),
                ("glasgowQty", models.IntegerField(default=0)),
                ("edinburghQty", models.IntegerField(default=0)),
                ("newcastleQty", models.IntegerField(default=0)),
                ("guitarType", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.TextField()),
                ("type", models.TextField()),
            ],
        ),
    ]
