# Generated by Django 5.2.7 on 2025-10-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Guitars',
            fields=[
                ('sku', models.CharField(primary_key=True, serialize=False)),
                ('asn', models.CharField(null=True)),
                ('Category', models.CharField()),
                ('online', models.BinaryField()),
                ('itemName', models.CharField()),
                ('title', models.CharField(null=True)),
                ('brandName', models.CharField()),
                ('productDetail', models.TextField()),
                ('SalesPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pictureMain', models.ImageField(upload_to='')),
                ('qtyInStock', models.IntegerField(default=0)),
                ('qtyOnOrder', models.IntegerField(default=0)),
                ('colour', models.IntegerField()),
                ('pickup', models.IntegerField()),
                ('BodyShape', models.IntegerField()),
                ('CreatedOn', models.DateField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glasgowQty', models.IntegerField(default=0)),
                ('edinburghQty', models.IntegerField(default=0)),
                ('newcastleQty', models.IntegerField(default=0)),
                ('guitarType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarguitar.genres')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarguitar.type')),
            ],
        ),
    ]
