# Generated by Django 5.2.7 on 2025-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarguitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitars',
            name='online',
            field=models.CharField(),
        ),
    ]
