# Generated by Django 5.2.7 on 2025-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarguitar', '0002_alter_guitars_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='type',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
